name: GHAS Alert Collection

on:
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: alerts
        with:
          github-token: ${{ secrets.PAT }}
          result-encoding: string
          script: |
            const dependabot = await github.paginate('GET /orgs/{org}/dependabot/alerts', {
              org: 'Coveros',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28',
                'Accept': 'application/vnd.github+json'
              }
            });

            const codescanning = await github.paginate('GET /orgs/{org}/code-scanning/alerts', {
              org: 'Coveros',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28',
                'Accept': 'application/vnd.github+json'
              }
            });

            const secretscanning = await github.request('GET /orgs/{org}/secret-scanning/alerts', {
              org: 'Coveros',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28',
                'Accept': 'application/vnd.github+json'
              }
            });
            
            const json = JSON.stringify({ "dependabot-alerts": dependabot, "code-scanning-alerts": codescanning, "secret-scanning-alerts": secretscanning });
            
            const fs = require('fs');
            fs.writeFile('alerts.json', json, 'utf8', () => {});
            
            return json;

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: alerts
          path: alerts.json
